language: ruby

rvm:
- 2.2.4

addons:
  chrome: stable
  sauce_connect: true

before_install:
  - gem update bundler
  - bundle install
  - nvm install $(cat .nvmrc)

install:
  # Download ngrok
  - curl -sO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip $PWD/ngrok-stable-linux-amd64.zip
  - chmod +x $PWD/ngrok
  # Download json parser for determining ngrok tunnel
  - curl -sO http://stedolan.github.io/jq/download/linux64/jq
  - chmod +x $PWD/jq

script: ./scripts/travis.sh

dist: trusty

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SAUCE_BROWSER_NAME="chrome"
  - SAUCE_BROWSER_VERSION=""
  - SAUCE_PLATFORM="Windows 10"
  - SAUCE_APPIUM_VERSION=""
  - SAUCE_DEVICE_NAME=""
  - SAUCE_DEVICE_ORIENTATION=""
  - SAUCE_PLATFORM_VERSION=""
  - SAUCE_PLATFORM_NAME=""
  - secure: RW99TW7YvGgWt/P8fQQziPbxNITaJMO/4q2iCX72u/PtTu2dkeaCqUiRUi7qyV8jIIk7U4oruxJRFQpTaCIX5+JWZsSwLskoTsspOI9aTzyPdhVNckM1vpA5VfwstdyQTkX7zzKPLdvXK0xj0ZzQ+ACH/SobQNYKiAMvW7FVkIc=
  - secure: gFSORYQLSBNIK8peGgUOhd0Yj6GzE18HA0GLrmp0PMtobe003poalkNgLsPy2W2QFZbG3bCjbqFMmCbUh5uRnX8eCy/whe+lwXeQsv5uh0EIGWgxVxhk79dCx5cakERusoj2BUgJJ432R7nRXjEW5v2AK9QAOeCG2Dvwdb8WSes=

deploy:
  provider: script
  script: scripts/gh-pages-publish.sh
  on:
    branch: source
